apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loan-backend
  template:
    metadata:
      labels:
        app: loan-backend
    spec:
      containers:
        - name: loan-backend
          image: akshaysubbaram/loan-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 9898

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9898
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9898
            initialDelaySeconds: 10
            periodSeconds: 5

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"