apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loan-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: loan-strategy-calculator.local
      http:
        paths:
          - path: /loan(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: loan-backend-service
                port:
                  number: 9898